gtk2:
	gcc -std=c99 `pkg-config --cflags gtk+-2.0` fenster.c -o fenster1 `pkg-config --libs gtk+-2.0`
	./fenster1

gtk3:
	gcc -g -std=c99 `pkg-config --cflags gtk+-3.0` fenster.c -o fenster1 `pkg-config --libs gtk+-3.0`
	./fenster1
